"""Invitation tokens and recovery codes.

**These are hashed with SHA-256, not argon2, and that is not an oversight.**
argon2 exists to make guessing a *low-entropy human choice* expensive. Both
values here are generated by `secrets` with at least 60 bits of entropy, so
guessing is already infeasible and the only thing argon2 would add is latency
on a path an unauthenticated caller can trigger. What matters is that the
plaintext is never stored, which is what stops a database read from yielding a
usable link. See docs/architecture/security.md section 5.4.

The comparison side matters as much: a recovery code is checked by hashing the
presented value and comparing digests in constant time, never by looking the
plaintext up.
"""

from __future__ import annotations

import hashlib
import secrets
from dataclasses import dataclass

TOKEN_BYTES = 32
"""256 bits for invitation and reset links. They travel in a URL, may be
copied through a chat client, and are the only thing standing between a
stranger and an account."""

RECOVERY_CODE_COUNT = 10

RECOVERY_ALPHABET = "abcdefghjkmnpqrstuvwxyz23456789"
"""Crockford-ish: no `i`/`l`/`1`, no `o`/`0`. These are transcribed by hand
from a screen, sometimes from paper, and an ambiguous glyph turns a recovery
into a support request at the worst possible moment."""

RECOVERY_GROUPS = 3
RECOVERY_GROUP_LENGTH = 4
"""12 characters over a 31 symbol alphabet is about 59 bits, grouped for
legibility. Far beyond guessing, and the login path is rate limited anyway."""


@dataclass(frozen=True, slots=True)
class IssuedToken:
    plaintext: str
    """Exists exactly once, in the response that issued it. Never stored,
    never logged, never recoverable."""

    hashed: str


def _digest(value: str) -> str:
    return hashlib.sha256(value.encode()).hexdigest()


class TokenService:
    def issue_token(self) -> IssuedToken:
        plaintext = secrets.token_urlsafe(TOKEN_BYTES)
        return IssuedToken(plaintext=plaintext, hashed=_digest(plaintext))

    def hash_token(self, plaintext: str) -> str:
        """Used on the lookup side. The stored column is unique and indexed, so
        an unknown token costs one index probe and produces the same error as
        an expired or consumed one."""
        return _digest(plaintext)

    def issue_recovery_codes(self, count: int = RECOVERY_CODE_COUNT) -> list[IssuedToken]:
        return [self._recovery_code() for _ in range(count)]

    def hash_recovery_code(self, presented: str) -> str:
        """Normalised before hashing, so a code typed with the separators
        omitted or in a different case still matches. Normalisation is applied
        identically at issue time."""
        return _digest(_normalise_recovery_code(presented))

    def _recovery_code(self) -> IssuedToken:
        groups = [
            "".join(secrets.choice(RECOVERY_ALPHABET) for _ in range(RECOVERY_GROUP_LENGTH))
            for _ in range(RECOVERY_GROUPS)
        ]
        plaintext = "-".join(groups)
        return IssuedToken(plaintext=plaintext, hashed=_digest(_normalise_recovery_code(plaintext)))


def _normalise_recovery_code(value: str) -> str:
    return "".join(c for c in value.lower() if c in RECOVERY_ALPHABET)
