"""Document storage on a mounted volume.

ARCHITECTURE.md listed MinIO for this. It is a volume instead, decided when the
knowledge base was built: MinIO is another service to run, another set of
default credentials to replace (`minioadmin`/`minioadmin`, named in
security.md section 10), and another CVE surface, and this deployment is one
node with one filesystem. What MinIO would have bought — presigned URLs,
per-tenant credentials, horizontal storage — none of it is used here. The
decision is recorded in ARCHITECTURE.md section 6 and is the point to revisit
if a second node ever needs to read the same documents.

**No caller supplies a path.** The layout is `<root>/<tenant_id>/<document_id>/`
with fixed leaf names, and both ids are UUIDs this platform generated and this
adapter re-validates. A filename never appears in it, so the traversal that
usually accompanies file upload has no argument to travel through.
"""

from __future__ import annotations

import asyncio
import re
import shutil
from pathlib import Path

from app.domain.exceptions import DocumentNotFoundError

_ID = re.compile(r"\A[0-9a-fA-F-]{36}\Z")
"""Ids are generated by `uuid.uuid4()`, so this is a restatement of a fact
rather than a filter over untrusted input. It is here because the cost of being
wrong about that is arbitrary filesystem access, and the assumption is one
refactor away from silently changing."""

ORIGINAL_NAME = "original.bin"
TEXT_NAME = "extracted.txt"
"""Fixed leaf names, with no extension taken from the upload. The original is
stored under a neutral name because it is never served back by path and nothing
should be tempted to infer a type from it: the media type is a database column.
"""


class FilesystemDocumentStorage:
    """Scoped to one tenant, like the tenant-scoped repositories.

    A tenant appears in the path, and the tenant comes from the actor at
    construction rather than from any argument, so reading another tenant's
    document is not a check that could be forgotten but a path that is not
    reachable. See docs/architecture/security.md section 7.3.
    """

    def __init__(self, root: Path | str, tenant_id: str) -> None:
        self._root = Path(root)
        if not _ID.match(tenant_id):
            raise ValueError(f"tenant id is not a uuid: {tenant_id!r}")
        self._tenant_id = tenant_id

    # --- writes ----------------------------------------------------------

    async def put_original(self, document_id: str, data: bytes) -> None:
        await asyncio.to_thread(self._write_bytes, self._path(document_id, ORIGINAL_NAME), data)

    async def put_text(self, document_id: str, text: str) -> None:
        await asyncio.to_thread(
            self._write_bytes, self._path(document_id, TEXT_NAME), text.encode("utf-8")
        )

    # --- reads -----------------------------------------------------------

    async def read_original(self, document_id: str) -> bytes:
        return await asyncio.to_thread(self._read_bytes, self._path(document_id, ORIGINAL_NAME))

    async def read_text(self, document_id: str) -> str:
        raw = await asyncio.to_thread(self._read_bytes, self._path(document_id, TEXT_NAME))
        return raw.decode("utf-8", errors="replace")

    # --- deletion --------------------------------------------------------

    async def delete(self, document_id: str) -> None:
        await asyncio.to_thread(self._remove_tree, self._directory(document_id))

    # --- internals -------------------------------------------------------
    #
    # Blocking file I/O in threads. A 32 MiB write is milliseconds on an SSD but
    # it is still a syscall that parks the thread, and this runs inside the same
    # event loop that is streaming completions.

    def _directory(self, document_id: str) -> Path:
        if not _ID.match(document_id):
            raise DocumentNotFoundError(detail=f"document id is not a uuid: {document_id!r}")
        return self._root / self._tenant_id / document_id

    def _path(self, document_id: str, leaf: str) -> Path:
        return self._directory(document_id) / leaf

    @staticmethod
    def _write_bytes(path: Path, data: bytes) -> None:
        path.parent.mkdir(parents=True, exist_ok=True)
        # Write to a sibling and rename, so a crash or a full disk leaves either
        # the previous content or none, never a half file that would parse as a
        # truncated document.
        temporary = path.with_suffix(path.suffix + ".partial")
        temporary.write_bytes(data)
        temporary.replace(path)

    @staticmethod
    def _read_bytes(path: Path) -> bytes:
        try:
            return path.read_bytes()
        except FileNotFoundError as exc:
            raise DocumentNotFoundError(detail=f"no stored object at {path.name}") from exc

    @staticmethod
    def _remove_tree(directory: Path) -> None:
        # Idempotent: a row whose bytes are already gone must still be
        # deletable, or a failed upload leaves an undeletable document.
        shutil.rmtree(directory, ignore_errors=True)
