"""tighten constraints found by review

Revision ID: 6ab1a0eec2d1
Revises: a30a2c33edc3
Create Date: 2026-07-24 21:44:54.205692

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "6ab1a0eec2d1"
down_revision: str | None = "a30a2c33edc3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Hand-written: Alembic does not autogenerate check constraints, so this
    # would have been silently omitted. The invariant it enforces ("an account
    # never exists in a password-only state") was previously only a Python
    # property, which a direct write or a half-finished invitation could
    # violate.
    op.create_check_constraint(
        "ck_users_password_implies_totp",
        "users",
        "(password_hash IS NULL) = (totp_secret IS NULL)",
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "api_keys", "expires_at", existing_type=postgresql.TIMESTAMP(timezone=True), nullable=False
    )
    op.create_index(
        "ix_invitations_user_purpose", "invitations", ["user_id", "purpose"], unique=False
    )
    op.create_index(op.f("ix_recovery_codes_user_id"), "recovery_codes", ["user_id"], unique=False)
    op.alter_column(
        "usage_records",
        "api_key_id",
        existing_type=sa.VARCHAR(length=36),
        type_=sa.String(length=32),
        existing_nullable=True,
    )
    op.drop_index(op.f("ix_usage_records_api_key_id"), table_name="usage_records")
    op.create_index("ix_usage_key_at", "usage_records", ["api_key_id", "at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_usage_key_at", table_name="usage_records")
    op.create_index(
        op.f("ix_usage_records_api_key_id"), "usage_records", ["api_key_id"], unique=False
    )
    op.alter_column(
        "usage_records",
        "api_key_id",
        existing_type=sa.String(length=32),
        type_=sa.VARCHAR(length=36),
        existing_nullable=True,
    )
    op.drop_index(op.f("ix_recovery_codes_user_id"), table_name="recovery_codes")
    op.drop_index("ix_invitations_user_purpose", table_name="invitations")
    op.alter_column(
        "api_keys", "expires_at", existing_type=postgresql.TIMESTAMP(timezone=True), nullable=True
    )
    # ### end Alembic commands ###
    op.drop_constraint("ck_users_password_implies_totp", "users", type_="check")
