import { CodeBlock } from '@/components/composed/code-block';

type ResponseSectionProps = {
  sample: string;
};

export function ResponseSection({ sample }: ResponseSectionProps) {
  return (
<section className="space-y-3">
        <h2 className="font-heading text-base font-semibold">
          Tool calling, and agent clients
        </h2>
        <p className="text-sm text-muted-foreground">
          Send <code>tools</code> and the model may answer with a call instead
          of prose. <strong>The platform never runs a tool.</strong> You execute
          it and send the result back as a message with role{' '}
          <code>tool</code>, quoting the <code>tool_call_id</code> from the call
          you are answering. That round trip is the whole mechanism, and it is
          what a coding agent such as Codex is doing on every turn.
        </p>
        <CodeBlock
          code={`{
  "model": "${sample}",
  "messages": [
    {"role": "user", "content": "what is in this directory"},
    {"role": "assistant", "content": null,
     "tool_calls": [{"id": "call_1", "type": "function",
                     "function": {"name": "sh", "arguments": "{\\"cmd\\":\\"ls\\"}"}}]},
    {"role": "tool", "tool_call_id": "call_1", "content": "a.txt b.txt"}
  ],
  "tools": [{"type": "function", "function": {
    "name": "sh", "description": "Run a shell command",
    "parameters": {"type": "object", "properties": {"cmd": {"type": "string"}}}
  }}]
}`}
          label="Copy the round trip"
        />
        <dl className="grid gap-x-4 gap-y-2 text-sm sm:grid-cols-[10rem_1fr]">
          <dt className="font-mono text-muted-foreground">finish_reason</dt>
          <dd>
            <code>tool_calls</code> when the model asked for one. Branch on it:
            it is how you tell &quot;run this and come back&quot; from an answer
            you should show someone.
          </dd>
          <dt className="font-mono text-muted-foreground">tool_call_id</dt>
          <dd>
            Generated by this platform, because the runtimes underneath do not
            all mint one. Send back exactly what you received; it is the only
            thing pairing your result with the request that caused it.
          </dd>
          <dt className="font-mono text-muted-foreground">arguments</dt>
          <dd>
            A JSON <em>string</em>, as OpenAI defines it, and passed through
            exactly as the model produced it.{' '}
            <strong>It is model output, so it can be malformed</strong> — parse
            defensively. Replaying a turn whose arguments do not parse is
            refused with <code>400 runtime_capability_unsupported</code> when
            the serving runtime takes arguments as an object, as Ollama does
            (measured 2026-08-05; this page said the opposite before that
            date). Repair or drop that turn — retrying replays the failure.
          </dd>
          <dt className="font-mono text-muted-foreground">tool_choice</dt>
          <dd>
            <code>auto</code> (the default) and <code>none</code> work.{' '}
            <code>required</code> and naming a function are refused with{' '}
            <code>400 runtime_capability_unsupported</code>: neither runtime
            here can force a call, and quietly giving you <code>auto</code>{' '}
            would answer a demand for a call with prose.
          </dd>
        </dl>
        <p className="text-sm text-muted-foreground">
          <strong>Tool definitions count towards the context limit</strong>, as
          does the call history you replay. A long agent conversation reaches
          the 413 below through accumulated tool output rather than through any
          single large message.
        </p>
        <p className="text-sm text-muted-foreground">
          Streaming delivers each call as one{' '}
          <code>delta.tool_calls</code> entry with a complete{' '}
          <code>arguments</code> string, rather than as the many fragments
          OpenAI sends. A client that concatenates fragments handles this
          correctly without changes — concatenating one piece is that piece —
          and the <code>index</code> field is present and runs across the whole
          stream, so a client buffering on it behaves as it would elsewhere.
        </p>
        <p className="text-sm text-muted-foreground">
          <strong>Ask an administrator to turn deliberation off</strong> for the
          capability you point an agent at. A thinking model reasons again on
          every tool round trip, which multiplies the cost of a task by the
          number of steps in it, and it is set per capability on the routing
          policy rather than per request.
        </p>
      </section>
  );
}



export function ToolsSection() {
  return (
<section className="space-y-3">
        <h2 className="font-heading text-base font-semibold">
          Two wire protocols, and which one your client speaks
        </h2>
        <p className="text-sm text-muted-foreground">
          Everything above describes{' '}
          <code>POST /v1/chat/completions</code>, which is the documented
          interface and unchanged. Since 2026-08-07 the gateway also serves{' '}
          <code>POST /v1/responses</code>, OpenAI&apos;s newer Responses API,
          because some clients no longer speak the older one.{' '}
          <strong>
            Both route through the same policy, the same key checks and the same
            limits
          </strong>{' '}
          — only the shape on the wire differs, so the capability you ask for
          and the model that serves it are identical either way.
        </p>
        <dl className="grid gap-x-4 gap-y-2 text-sm sm:grid-cols-[10rem_1fr]">
          <dt className="font-mono text-muted-foreground">Codex</dt>
          <dd>
            Needs <code>/v1/responses</code>. It removed Chat Completions
            support in February 2026, so <code>wire_api = &quot;responses&quot;</code>{' '}
            is required in <code>~/.codex/config.toml</code> and{' '}
            <code>wire_api = &quot;chat&quot;</code> refuses to start.
          </dd>
          <dt className="font-mono text-muted-foreground">
            Most libraries
          </dt>
          <dd>
            The OpenAI SDKs, LangChain, Cline, Continue and anything taking a
            base URL use <code>/v1/chat/completions</code>. Nothing to change.
          </dd>
          <dt className="font-mono text-muted-foreground">Claude Code</dt>
          <dd>
            <strong>Cannot connect to this gateway.</strong> It speaks
            Anthropic&apos;s Messages API (<code>/v1/messages</code>), which the
            platform does not serve. A translating proxy in front is the only
            route today.
          </dd>
        </dl>
        <p className="text-sm text-muted-foreground">
          The Responses API carries tools <em>flat</em> —{' '}
          <code>
            {'{"type": "function", "name": ..., "parameters": ...}'}
          </code>{' '}
          — where Chat Completions nests them under a{' '}
          <code>function</code> key, and its system prompt arrives as a
          top-level <code>instructions</code> string rather than as a message.
          The platform translates both onto the same request, so this only
          matters if you are writing the client yourself.
        </p>
        <p className="text-sm text-muted-foreground">
          <strong>Server-side tools are not served.</strong> A{' '}
          <code>web_search</code> tool is refused with{' '}
          <code>400 runtime_capability_unsupported</code> when the client
          actually enables it — performing one would mean this gateway making
          outbound web requests, which it deliberately cannot do. A disabled
          one, and any tool type this platform does not recognise, is dropped
          instead and named in the <code>X-Dropped-Tools</code> response header,
          so a capability the model never saw is findable rather than a mystery.
          An input item on <code>/v1/responses</code> whose type this gateway
          does not recognise is dropped the same way — part of the conversation
          never reaches the model — and named in{' '}
          <code>X-Dropped-Input-Items</code>. Both are narrowings rather than
          failures, and both are announced rather than silent.
        </p>
        <p className="text-sm text-muted-foreground">
          <strong>
            A key may carry a default capability, and the response says when it
            fired.
          </strong>{' '}
          The <code>model</code> field takes a capability, and a key issued with
          a default serves one of its own rather than refusing when a request
          names anything else — which is what makes a client that insists on
          sending its own model name work. It is off unless an administrator
          turned it on for that key, it can only ever name a capability the key
          already holds, and every substituted request carries{' '}
          <code>X-Capability-Defaulted</code> with the capability that actually
          ran. Read that header before concluding your <code>model</code> line
          is the one in use.
        </p>
      </section>
  );
}


export function GroundingSection() {
  return (
<section className="space-y-3">
        <h2 className="font-heading text-base font-semibold">
          Grounding on the knowledge base
        </h2>
        <p className="text-sm text-muted-foreground">
          With <code>use_knowledge: true</code> the platform embeds your latest
          question, retrieves passages from your tenant&apos;s documents, and
          puts them in front of the model as data. The frames themselves stay
          strictly OpenAI-shaped; which passages were used comes back as a
          response header, because an extra frame shape would be a protocol
          error to a client that parses the envelope strictly.
        </p>
        <CodeBlock
          code={'X-Knowledge-Sources: <document id>:<passage>,<document id>:<passage>'}
          label="Copy the header name"
        />
        <p className="text-sm text-muted-foreground">
          Ids and passage indexes only, never passage text — a header reaches
          access logs. The header is present on both the streaming and
          non-streaming paths, and is <strong>absent when nothing was
          retrieved</strong>.
        </p>
        <p className="text-sm text-muted-foreground">
          <strong>Retrieval usually degrades rather than failing.</strong> If
          the vector store is unreachable, or this deployment has no embedding
          model routed, or your question matched nothing, you get an ordinary
          ungrounded completion: 200, no header, no error. That is deliberate —
          an outage in an enhancement should not turn a working chat into a 503
          — and it means <code>use_knowledge: true</code> is a request rather
          than a guarantee. If your application depends on an answer being
          grounded, check for the header rather than assuming it.
        </p>
        <p className="text-sm text-muted-foreground">
          <strong>Two conditions are not survivable, and both fail the whole
          request rather than the retrieval.</strong> If the routed embedding
          model is missing from its runtime you get{' '}
          <code>404 model_not_found</code>, and if it sits on a runtime that
          cannot embed at all you get{' '}
          <code>400 runtime_capability_unsupported</code>. Neither can happen to
          the same request without <code>use_knowledge</code>, so dropping the
          flag is a workaround while an administrator fixes the{' '}
          <code>embedding</code> policy. Both are deployment faults; retrying
          identically will not clear either.
        </p>
      </section>
  );
}



export function StreamingSection() {
  return (
<section className="space-y-3">
        <h2 className="font-heading text-base font-semibold">
          One measured limit of the models, not of the API
        </h2>
        <p className="text-sm text-muted-foreground">
          <strong>
            A model here will answer a question its input cannot answer.
          </strong>{' '}
          Measured on this deployment on 2026-08-15, against a task whose data
          does not determine the result: every model tested returned a confident
          figure rather than reporting the gap — nine samples out of nine, with
          the working shown. It is a property of the models rather than of this
          platform, so it is not addressed by choosing a different capability,
          by <code>use_knowledge</code>, or by any field in this document.
        </p>
        <p className="text-sm text-muted-foreground">
          It is here because it has a bearing on how you write a client. An
          application that shows a model&apos;s answer to a person can note
          where it came from; one that parses a number out of it and acts on it
          has no signal to branch on, because a fabricated answer is
          well-formed, arrives with <code>finish_reason: &quot;stop&quot;</code>{' '}
          and looks exactly like a correct one. Where a wrong answer costs
          something, have the model produce the inputs and do the arithmetic
          yourself.
        </p>
      </section>
  );
}
