import { CodeBlock } from '@/components/composed/code-block';

type ResponseSectionProps = {
  sample: string;
};

export function ResponseSection({ sample }: ResponseSectionProps) {
  return (
<section className="space-y-3">
        <h2 className="font-heading text-base font-semibold">
          Tool calling, and agent clients
        </h2>
        <p className="text-sm text-muted-foreground">
          Where <code>tools</code> is sent, the model may answer with a call
          rather than with prose. <strong>The platform never runs a tool.</strong>{' '}
          The caller executes it and returns the result as a message with role{' '}
          <code>tool</code>, quoting the <code>tool_call_id</code> from the call
          being answered. That round trip constitutes the entire mechanism, and
          it is what a coding agent such as Codex performs on every turn.
        </p>
        <CodeBlock
          code={`{
  "model": "${sample}",
  "messages": [
    {"role": "user", "content": "what is in this directory"},
    {"role": "assistant", "content": null,
     "tool_calls": [{"id": "call_1", "type": "function",
                     "function": {"name": "sh", "arguments": "{\\"cmd\\":\\"ls\\"}"}}]},
    {"role": "tool", "tool_call_id": "call_1", "content": "a.txt b.txt"}
  ],
  "tools": [{"type": "function", "function": {
    "name": "sh", "description": "Run a shell command",
    "parameters": {"type": "object", "properties": {"cmd": {"type": "string"}}}
  }}]
}`}
          label="Copy the round trip"
        />
        <dl className="grid gap-x-4 gap-y-2 text-sm sm:grid-cols-[10rem_1fr]">
          <dt className="font-mono text-muted-foreground">finish_reason</dt>
          <dd>
            <code>tool_calls</code> where the model requested one. Branch on
            this field: it distinguishes a request to execute and return from an
            answer intended for display.
          </dd>
          <dt className="font-mono text-muted-foreground">tool_call_id</dt>
          <dd>
            Generated by this platform, because the underlying runtimes do not
            all issue one. Return exactly the value received; it is the sole
            means of pairing a result with the request that produced it.
          </dd>
          <dt className="font-mono text-muted-foreground">arguments</dt>
          <dd>
            A JSON <em>string</em>, as OpenAI defines it, passed through exactly
            as the model produced it.{' '}
            <strong>It is model output and may therefore be malformed</strong>;
            parse defensively. Replaying a turn whose arguments do not parse is
            refused with <code>400 runtime_capability_unsupported</code> where
            the serving runtime takes arguments as an object, as Ollama does.
            Repair or discard that turn; retrying replays the failure.
          </dd>
          <dt className="font-mono text-muted-foreground">tool_choice</dt>
          <dd>
            <code>auto</code> (the default) and <code>none</code> are
            supported. <code>required</code> and naming a function are refused
            with <code>400 runtime_capability_unsupported</code>: no runtime
            here can compel a call, and substituting <code>auto</code> would
            answer a requirement for a call with prose.
          </dd>
        </dl>
        <p className="text-sm text-muted-foreground">
          <strong>Tool definitions count towards the context limit</strong>, as
          does the replayed call history. A long agent conversation reaches the
          413 described below through accumulated tool output rather than
          through any single large message.
        </p>
        <p className="text-sm text-muted-foreground">
          Streaming delivers each call as one <code>delta.tool_calls</code>{' '}
          entry with a complete <code>arguments</code> string, rather than as
          the several fragments OpenAI sends. A client that concatenates
          fragments handles this without modification, since concatenating a
          single piece yields that piece, and the <code>index</code> field is
          present and runs across the whole stream, so a client buffering on it
          behaves as it would elsewhere.
        </p>
        <p className="text-sm text-muted-foreground">
          <strong>Deliberation should be disabled</strong> on the capability an
          agent is pointed at. A deliberating model reasons again on every tool
          round trip, which multiplies the cost of a task by the number of steps
          it contains. The setting is per capability, on the routing policy,
          rather than per request, so an administrator applies it.
        </p>
      </section>
  );
}



export function ToolsSection() {
  return (
<section className="space-y-3">
        <h2 className="font-heading text-base font-semibold">
          Two wire protocols
        </h2>
        <p className="text-sm text-muted-foreground">
          The material above describes{' '}
          <code>POST /v1/chat/completions</code>, which is the documented
          interface and is unchanged. The gateway also serves{' '}
          <code>POST /v1/responses</code>, OpenAI&apos;s newer Responses API,
          because some clients no longer speak the older one.{' '}
          <strong>
            Both route through the same policy, the same key checks and the same
            limits.
          </strong>{' '}
          Only the shape on the wire differs, so the capability requested and
          the model that serves it are identical either way.
        </p>
        <dl className="grid gap-x-4 gap-y-2 text-sm sm:grid-cols-[10rem_1fr]">
          <dt className="font-mono text-muted-foreground">Codex</dt>
          <dd>
            Requires <code>/v1/responses</code>. OpenAI&apos;s current{' '}
            <a
              className="underline underline-offset-2"
              href="https://learn.chatgpt.com/docs/config-file/config-reference"
              rel="noreferrer"
              target="_blank"
            >
              configuration reference
            </a>{' '}
            documents only the Responses wire API, so{' '}
            <code>wire_api = &quot;responses&quot;</code> is required in{' '}
            <code>~/.codex/config.toml</code>, and{' '}
            <code>wire_api = &quot;chat&quot;</code> refuses to start in the
            measured clients. February 2026 is this project&apos;s observed
            compatibility boundary, not an OpenAI compatibility promise.
          </dd>
          <dt className="font-mono text-muted-foreground">
            Most libraries
          </dt>
          <dd>
            The OpenAI SDKs, LangChain, Cline, Continue and anything else
            accepting a base URL use <code>/v1/chat/completions</code>. No
            change is required.
          </dd>
          <dt className="font-mono text-muted-foreground">Claude Code</dt>
          <dd>
            <strong>Cannot connect to this gateway.</strong> It speaks
            Anthropic&apos;s Messages API (<code>/v1/messages</code>), which the
            platform does not serve. A translating proxy in front of the gateway
            is the only available route.
          </dd>
        </dl>
        <p className="text-sm text-muted-foreground">
          The Responses API carries tools <em>flat</em> —{' '}
          <code>
            {'{"type": "function", "name": ..., "parameters": ...}'}
          </code>{' '}
          — where Chat Completions nests them under a{' '}
          <code>function</code> key, and its system prompt arrives as a
          top-level <code>instructions</code> string rather than as a message.
          The platform translates both onto the same request, so the difference
          is material only to a client written directly against the wire.
        </p>
        <p className="text-sm text-muted-foreground">
          <strong>Server-side tools are not served.</strong> A{' '}
          <code>web_search</code> tool is refused with{' '}
          <code>400 runtime_capability_unsupported</code> where the client
          enables it, since performing one would require this gateway to make
          outbound web requests, which it is not permitted to do. A disabled
          tool, and any tool type this platform does not recognise, is dropped
          instead and named in the <code>X-Dropped-Tools</code> response header,
          so a capability the model never received is discoverable rather than
          unexplained. An input item on <code>/v1/responses</code> whose type
          the gateway does not recognise is dropped in the same way — part of
          the conversation therefore never reaches the model — and named in{' '}
          <code>X-Dropped-Input-Items</code>. Both are narrowings rather than
          failures, and both are declared rather than silent.
        </p>
        <p className="text-sm text-muted-foreground">
          <strong>
            A key may carry a default capability, and the response states when
            it was applied.
          </strong>{' '}
          The <code>model</code> field takes a capability, and a key issued with
          a default serves one of its own rather than refusing where a request
          names anything else, which is what allows a client that insists on
          sending its own model name to work. It is disabled unless an
          administrator has enabled it for that key, it can only name a
          capability the key already holds, and every substituted request
          carries <code>X-Capability-Defaulted</code> stating the capability
          that ran. Read that header before concluding that the{' '}
          <code>model</code> line is the one in use.
        </p>
      </section>
  );
}


export function GroundingSection() {
  return (
<section className="space-y-3">
        <h2 className="font-heading text-base font-semibold">
          Grounding on the knowledge base
        </h2>
        <p className="text-sm text-muted-foreground">
          With <code>use_knowledge: true</code> the platform embeds the most
          recent question, retrieves passages from the tenant&apos;s documents,
          and places them before the model as data. The frames themselves remain
          strictly OpenAI-shaped; the passages used are reported in a response
          header, because an additional frame shape would constitute a protocol
          error to a client that parses the envelope strictly.
        </p>
        <CodeBlock
          code={'X-Knowledge-Sources: <document id>:<passage>,<document id>:<passage>'}
          label="Copy the header name"
        />
        <p className="text-sm text-muted-foreground">
          Identifiers and passage indexes only, never passage text, since a
          header reaches access logs. The header is present on both the
          streaming and non-streaming paths, and is{' '}
          <strong>absent where nothing was retrieved</strong>.
        </p>
        <p className="text-sm text-muted-foreground">
          <strong>Retrieval degrades rather than failing.</strong> Where the
          vector store is unreachable, where the deployment has no embedding
          model routed, or where the question matched nothing, the result is an
          ordinary ungrounded completion: 200, no header, no error. An outage in
          an enhancement does not convert a working request into a 503, which
          means <code>use_knowledge: true</code> is a request rather than a
          guarantee. An application that depends on an answer being grounded
          must test for the header rather than assume it.
        </p>
        <p className="text-sm text-muted-foreground">
          <strong>
            Two conditions are not recoverable, and both fail the whole request
            rather than the retrieval.
          </strong>{' '}
          Where the routed embedding model is missing from its runtime, the
          result is <code>404 model_not_found</code>; where it sits on a runtime
          that cannot embed, the result is{' '}
          <code>400 runtime_capability_unsupported</code>. Neither can occur on
          the same request without <code>use_knowledge</code>, so removing the
          flag is a workaround while an administrator corrects the{' '}
          <code>embedding</code> policy. Both are deployment faults, and an
          identical retry clears neither.
        </p>
      </section>
  );
}



export function StreamingSection() {
  return (
<section className="space-y-3">
        <h2 className="font-heading text-base font-semibold">
          A measured limit of the models, not of the API
        </h2>
        <p className="text-sm text-muted-foreground">
          <strong>
            A model on this deployment will answer a question its input cannot
            determine.
          </strong>{' '}
          Measured against a task whose data does not determine the result,
          every model tested returned a confident figure rather than reporting
          the deficiency, in every sample, with the working set out. This is a
          property of the models rather than of this platform, so it is not
          addressed by selecting a different capability, by{' '}
          <code>use_knowledge</code>, or by any field in this document.
        </p>
        <p className="text-sm text-muted-foreground">
          It is stated here because it bears on client design. An application
          that presents a model&apos;s answer to a person can indicate its
          provenance; one that parses a figure out of it and acts on that figure
          has no signal to branch on, because a fabricated answer is
          well-formed, arrives with <code>finish_reason: &quot;stop&quot;</code>{' '}
          and is indistinguishable from a correct one. Where a wrong answer
          carries a cost, have the model produce the inputs and perform the
          arithmetic in the client.
        </p>
      </section>
  );
}
