"""Persistence ports.

Grouped in one module because they share a shape and are always implemented
together by the same adapter package. The domain depends on these Protocols
only; nothing here knows about SQLAlchemy.
"""

from __future__ import annotations

from datetime import datetime
from typing import Protocol

from app.domain.entities.api_key import ApiKey
from app.domain.entities.invitation import Invitation, InvitationPurpose, RecoveryCode
from app.domain.entities.model import Model, ModelState
from app.domain.entities.node import Node
from app.domain.entities.routing_policy import RoutingPolicy
from app.domain.entities.usage import UsageRecord
from app.domain.entities.user import User


class ModelRepositoryPort(Protocol):
    async def get(self, model_id: str) -> Model | None: ...
    async def get_by_alias(self, alias: str) -> Model | None: ...
    async def list_all(self) -> list[Model]: ...
    async def list_loaded(self, node_id: str) -> list[Model]: ...
    async def save(self, model: Model) -> None: ...
    async def set_state(self, model_id: str, state: ModelState) -> None: ...


class NodeRepositoryPort(Protocol):
    async def get(self, node_id: str) -> Node | None: ...
    async def list_all(self) -> list[Node]: ...
    async def save(self, node: Node) -> None: ...


class RoutingPolicyRepositoryPort(Protocol):
    async def get(self, capability: str) -> RoutingPolicy | None: ...
    async def list_all(self) -> list[RoutingPolicy]: ...
    async def save(self, policy: RoutingPolicy) -> None: ...


class ApiKeyRepositoryPort(Protocol):
    async def get_by_key_id(self, key_id: str) -> ApiKey | None: ...
    async def list_for_owner(self, owner_id: str) -> list[ApiKey]: ...
    async def save(self, key: ApiKey) -> None: ...
    async def revoke(self, key_id: str, at: datetime) -> None: ...


class UserRepositoryPort(Protocol):
    async def get(self, user_id: str) -> User | None: ...
    async def get_by_login(self, login: str) -> User | None: ...
    async def get_by_tailscale_login(self, login: str) -> User | None: ...
    async def list_all(self) -> list[User]: ...
    async def count(self) -> int:
        """Used by the bootstrap check: the first-admin setting is inert once
        any user exists."""
        ...

    async def save(self, user: User) -> None: ...


class InvitationRepositoryPort(Protocol):
    async def get_by_token_hash(self, token_hash: str) -> Invitation | None: ...
    async def save(self, invitation: Invitation) -> None: ...
    async def consume(self, invitation_id: str, at: datetime) -> None: ...
    async def invalidate_outstanding(self, user_id: str, purpose: InvitationPurpose) -> None: ...

    async def save_recovery_codes(self, codes: list[RecoveryCode]) -> None: ...
    async def list_recovery_codes(self, user_id: str) -> list[RecoveryCode]: ...
    async def consume_recovery_code(self, code_id: str, at: datetime) -> None: ...


class UsageRepositoryPort(Protocol):
    async def record(self, usage: UsageRecord) -> None: ...
    async def tokens_used_today(self, api_key_id: str) -> int: ...
